language: ruby
rvm:
- 2.2.4
env:
  global:
    secure: PHESHNcZauyUCRcLvEnr/2sArQIvpYaF9F9yez2nS6rygUBL8LOwphLOIwdRp6kXMn99+qpr24HNQT4NNNt75D5IYu99TqEKJmONIjkOJwwc3GFhyIHU+4ootWPeNgdM9fN74I5SeTBKsHuJW39HGLzo8Erjq86esZ8iF5j/Aw719hIYinW3uykjy+oYmulxb1TGLHLT1qqkvgC5oP3/YH4cc3slOHePTqucczKFqp6XHxULoQ3iClsTbayvFZFmeUVE3aXYIIH/aXx8+tzGImbOa8TCetXOCoT035vgUK2OPUF2stF+PzXO9C8SZaVm+6C6dMGz0l9pkk+6XYKBbhf/EEiU3bGY69SokFLC5hgOOVyUAl23FAqtHJMPP6GBv9h7y4Y055q5z/Drd7QZoX7C3bvoIh4Rxld2nq67iZHAhIPdeonz5jsxXk812Woq8PCJtc9j+T/dw08//HLPJp2bUGCgENNfvoPxD6zaDgcVtul8EMAMNFuXOJSXr4/+j8YLLVhGM19PPHNm6JR+HCSR+qx4km/KMWGou1b3eIwXkotKljt/0YDc3kdlokSEfbKDqc639R2g+QKXVabiXfwSkaeF4v/7JWxvCVjJP+pciB/CSZ/VknGIS7l5ROW565IO5n2RN95B853qxmOLbkpyTRahBvMbVE8m96H2i80=
addons:
  code_climate:
    repo_token: 3c579ab336b804379c97fcc7a18d58a9cf87084e7e05b24c97c22035b40122ae
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
after_success:
- curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge
- chmod a+x /tmp/travis-automerge
- BRANCHES_TO_MERGE_REGEX='^issue#' BRANCH_TO_MERGE_INTO=desenvolvimento GITHUB_REPO=PurrSuit/backend_purrsuit
  /tmp/travis-automerge
deploy:
  provider: heroku
  api_key:
    secure: H3VOC4CKxkukOMVMlLdpYDMhNScRHilzebK/ihi1nYJd/tqASOT7salhjUqlnH03o9PHKlRdOvQTUCPqymmM6+qsJYX35wGMHSlXHuW/IUE7PTQc19EvZ2AAsKwxu5+xbxdINmlTeP4AkQY/yGoArMffBTTUST9865YS99R2m+sLfV0/SoV2wBNVHDP+pfPgWKrAYaj45Nta1sl+3S3PR/1IvVQotJlfE/5WfrQY4fQM8hsCxjOqKE3cFYHUlG2S3oRGKcOsUhwfH1uUcERioLEgXlbOrLyJTdQrrxC69Ji64xnCp4KK4pj5Gp+nk9kb6UwoolWdRoawAQBbmIe4CFOwIANao7bewf5zCe+VeD7zg5rA2R859+8anPntKKkYAAty9+HIguXQOzO1PJTI+xpDjD99mLlp8qYIcqIXU5BbFwOi+cTTV1MSODYo3jCVA2PJ/40AfvTw93BULrcnRm/+/jT81Na5r+zk90fyO5/S4dQcKB1PjLzEPvTXILmEd3IRXP8FQSEHsweeSy1o6DX/kMo8l4Nf3sM7ic3vqWqbjS5oVyFGl7lIepXGeh/afirWJQoGRZzshcbqma6uQZGweLawmqPnMQyeyF9yvtkAyyWPwnSIl5XPdtvzHJsaRSdcmQM1LPyFuA9q+zgbdc+iZ3wv9/e2ev4zI722lJ0=
  app:
    desenvolvimento: purrsuit-staging
    master: purrsuit-production
  on:
    repo: PurrSuit/backend_purrsuit
