language: ruby
rvm:
- 2.2.4
env:
  global:
    secure: PHESHNcZauyUCRcLvEnr/2sArQIvpYaF9F9yez2nS6rygUBL8LOwphLOIwdRp6kXMn99+qpr24HNQT4NNNt75D5IYu99TqEKJmONIjkOJwwc3GFhyIHU+4ootWPeNgdM9fN74I5SeTBKsHuJW39HGLzo8Erjq86esZ8iF5j/Aw719hIYinW3uykjy+oYmulxb1TGLHLT1qqkvgC5oP3/YH4cc3slOHePTqucczKFqp6XHxULoQ3iClsTbayvFZFmeUVE3aXYIIH/aXx8+tzGImbOa8TCetXOCoT035vgUK2OPUF2stF+PzXO9C8SZaVm+6C6dMGz0l9pkk+6XYKBbhf/EEiU3bGY69SokFLC5hgOOVyUAl23FAqtHJMPP6GBv9h7y4Y055q5z/Drd7QZoX7C3bvoIh4Rxld2nq67iZHAhIPdeonz5jsxXk812Woq8PCJtc9j+T/dw08//HLPJp2bUGCgENNfvoPxD6zaDgcVtul8EMAMNFuXOJSXr4/+j8YLLVhGM19PPHNm6JR+HCSR+qx4km/KMWGou1b3eIwXkotKljt/0YDc3kdlokSEfbKDqc639R2g+QKXVabiXfwSkaeF4v/7JWxvCVjJP+pciB/CSZ/VknGIS7l5ROW565IO5n2RN95B853qxmOLbkpyTRahBvMbVE8m96H2i80=
addons:
  code_climate:
    repo_token: 3c579ab336b804379c97fcc7a18d58a9cf87084e7e05b24c97c22035b40122ae
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
after_success:
- curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge
- chmod a+x /tmp/travis-automerge
- BRANCHES_TO_MERGE_REGEX='^issue#' BRANCH_TO_MERGE_INTO=desenvolvimento GITHUB_REPO=PurrSuit/backend_purrsuit
  /tmp/travis-automerge
deploy:
  provider: heroku
  api_key:
    secure: oasBGSnTGQR7dtnk6ttF94E7dBr7AzAionKHdxt1FuhIVCk8gc1gE9pAzgWIxnZq1azll0kym3mfkiiDB52i/VYNE+WDJ0Z+k6tSz1YTwt1+vRkDBYARVmRXkLoBNWTIMU2CzrXY4igXEXZtkU7RafM/r99OUklVOcMMCy0mGDwnc7U3fZLXTm3hmx0xgs78VD6oTSkQRWnumpqkQs70EVzYfdH/piciz1xjcPN/WB+TN/GwMynCaXszO5cNjULXFxvvzPrcK5EZ29mDfZs9509EwV3nLRmHr4Y8c8nimlcgpmAtLX9GwCZzcdPfAFSP0/Wmt2bRBSJ6pBmEiEKk5I7Z7KA7X5Gg53Dwp+fEdjexEdhF+ewKedwk0FXMxjEblOA76WVgcwoW5onIP3Jv09Rd5WByl0AHPPztrd+2IOKxSrtAXK/2B5onIJ2T8aDshD6eOCzir5AU0203a9Pl/QbecuGs+vFwqlEgKgjSWGav+UMrh7iTPAHJQfHLfq+5B5lSsY1pD7o0sr58twwzFBVFBlgqIHixtkGhLoc/f6Yh+I/5oE1JP8oPTI2/DKLDpO/oHqGkZapjBS66mnlGAn+s00UgGczjqGCR66zv3i0pvif9bg/g5qDEOZUBWeNg+7gp7firQufmIsMpJeH9tD8zOJD6InmA1DEtkF4vj+Q=
  app:
    master: purrsuit-production
    desenvolvimento: purrsuit-staging
  run:
    - "rake db:drop"
    - "rake db:create"
    - "rake db:migrate"
    - "rake parse:deputies"
    - "rake parse:levels"
  on:
    branch: master
    run:
      - "rake parse:expenses"
